export const MOVE_PLAYER = 'MOVE_PLAYER'

export const REDUCE_STAMINA = 'REDUCE_STAMINA'

export const INCREASE_STAMINA = 'INCREASE_STAMINA'

export const PLAYER_MOVE_START = 'PLAYER_MOVE'
export const PLAYER_MOVE_SUCCESS = 'PLAYER_MOVE_SUCCESS'
export const PLAYER_MOVE_FAILURE = 'PLAYER_MOVE_FAILURE'