export const MOVE_PLAYER = 'MOVE_PLAYER'

export const REDUCE_STAMINA = 'REDUCE_STAMINA'

export const INCREASE_STAMINA = 'INCREASE_STAMINA'


export const PLAYER_MOVE_START = 'PLAYER_MOVE'
export const PLAYER_MOVE_SUCCESS = 'PLAYER_MOVE_SUCCESS'
export const PLAYER_MOVE_FAILURE = 'PLAYER_MOVE_FAILURE'

export const GET_CURRENT_ROOM = 'GET_CURRENT_ROOM'

export const INIT_PLAYER_START = 'INIT_PLAYER_START'
export const INIT_PLAYER_SUCCESS = 'INIT_PLAYER_SUCCESS'
export const INIT_PLAYER_FAILURE = 'INIT_PLAYER_FAILURE'

