//player types
export const PLAYER_DROP_START = "PLAYER_DROP_START"
export const PLAYER_DROP_SUCCESS = "PLAYER_DROP_SUCCESS"
export const PLAYER_DROP_FAILURE = "PLAYER_DROP_FAILURE"

export const PLAYER_EAT = 'PLAYER_EAT'

//room types
export const ROOM_TAKE_START = 'ROOM_TAKE_START'
export const ROOM_TAKE_SUCCESS = 'ROOM_TAKE_SUCCESS'
export const ROOM_TAKE_FAILURE = 'ROOM_TAKE_FAILURE'

//room and inventory items
export const GET_ROOMS_ITEMS = 'GET_ROOMS_ITEMS'

//GET ITEMS
export const GET_ITEMS_START = "GET_ITEMS_START"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE"

